name: Dev tests
on:
  workflow_call:
    secrets:
      CODECOV_CREDENTIALS:
        required: true

jobs:

  run:
    # Will read on PR dashboard as 'Deploy / DevTests / ubuntu'
    # Action dashboard identified by 'Dev tests'
    # Requirement settings identified as 'DevTests / ubuntu'
    name: ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Global Setup
        run: |
          python -m pip install -U pip
          pip install pytest-cov

      - name: Install local checkout
        run: pip install --no-cache-dir .

      - name: Display installed packages and their sources for debugging
        run: pip list

      - name: Run pytest with coverage and printout coverage for debugging
        run: |
          pytest -vv -rsx --cov=dandi_s3_log_parser --cov-report xml:./coverage.xml
          cat ./coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_CREDENTIALS }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
